### ISSUE TITLE
Malum stickerlar png değil

### ISSUE THREAD

**Issue by yusufusta** [kutlay1653/malum-sticker#1]
Arkaplanları beyaz, lütfen sonraki güncelleme de arkaplanları silin.

**Comment by kutlay1653** [comment]
amk ota mı verioz

**Comment by Clousry** [comment]
Brick olr 😮✌️

**Comment by yusufusta** [comment]
Lan nasıl ownersın sen kanglıcam reponu

**Comment by Tioxs** [comment]
çok iyi proje umarım devamı gelir

**Comment by kutlay1653** [comment]
> çok iyi proje umarım devamı gelir

inşallah kardeşim desteklerin için teşekkürler

**Comment by Clousry** [comment]
![sticker](https://user-images.githubusercontent.com/57768341/83354591-4bad6a00-a362-11ea-8c2f-93d9ef01c4c6.png)

**Comment by ripsivis** [comment]
Malûm stickerlar PNG.

**Comment by ripsivis** [comment]
![PicsArt_05-31-05 41 12](https://user-images.githubusercontent.com/57156687/83355128-1145cc00-a366-11ea-9bef-8b7227d60896.jpg)

**Comment by yusufusta** [comment]
Za

**Comment by kutlay1653** [comment]
elinize sağlık githubimi siktiniz ab

**Comment by Tioxs** [comment]
> elinize sağlık githubimi siktiniz ab

ne demek ab sağol 🥰

**Comment by Clousry** [comment]
> elinize sağlık githubimi siktiniz ab

rica ederim cnm

**Comment by kutlay1653** [comment]
arkadaşlar repoyu update ettim za

**Comment by yusufusta** [comment]
beğenmedim nerden dislike atıyoruz

**Comment by kutlay1653** [comment]
@Quiec yanlışlıkla editledim aq ama begeniom.bne

**Comment by badmaan** [comment]
geri döndü

**Comment by Quiec** [comment]
efsane
